### PR TITLE
create new registry

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
The ropensci.org/packages looks good with it https://deploy-preview-343--ropensci.netlify.com/packages/ (this roweb2 PR won't be merged, it was just to get the preview)

**Comment by maelle** [comment]
I have no idea when the encoding problem got fixed but my name is now correct :joy:

**Comment by maelle** [comment]
@cboettig you are in charge of reviewing the raw_cm.json file 😉 Do you think it's useful to publish it?

**Comment by maelle** [comment]
Some technical details:
* categories information stored in https://github.com/ropensci/roregistry/blob/gh-pages/final_categories.csv <- that file has to be curated by hand.
* code to make the registry in https://github.com/ropenscilabs/makeregistry
  * it's `codemetar` but with a few more assumptions:
     * if a package with the same name is on CRAN or Bioconductor it's assumed the package is on CRAN or Bioconductor, while `codemetar` is a bit more conservative in this regard (which I'm tempted to change, actually...), demanding a provider badge or that the local installed version comes from CRAN/Bioc.
    * if a repository has no status badge, it gets the status "concept" if it is in ropenscilabs, "active" otherwise (ropensci and others).
    * if for some reason the creation of the codemeta.json fails, if there's an entry in the older raw_cm.json, that entry is used.

**Comment by sckott** [comment]
@maelle 

- the website looks really good to me
- I think it's worth having the raw raw_cm.json file in the repo, we may want to use it 
- we have a number of packages that have the maintainer as `The package maintainer` - four of them - maybe we can exclude repos like these somehow?  One of them at least is archived on github, so maybe we can exclude those at least?

**Comment by maelle** [comment]
I archived all repos with the default maintainer. One of them was as you mentioned @sckott already archived but it was cloned which I do not understand. If a repo is cloned once, and then gets archived, does the corresponding folder get deleted?

**Comment by sckott** [comment]
> If a repo is cloned once, and then gets archived, does the corresponding folder get deleted?

do you mean on the server we're using?

**Comment by cboettig** [comment]
`raw_cm.json` 😍😍😍 

This all looks great!

**Comment by maelle** [comment]
> do you mean on the server we're using?

Yes

**Comment by sckott** [comment]
@maelle no, the script I have is pretty dumb, but there's only a few of those, so I can just edit the script accordingly

**Comment by sckott** [comment]
what is the list of repos again that are archived?

**Comment by maelle** [comment]
> what is the list of repos again that are archived?

Can you get the info dynamically from GitHub API before cloning?

**Comment by sckott** [comment]
probably, can try to integrate that

**Comment by maelle** [comment]
Thanks, it'd be nicer than recording which repos are archived :pray:

**Pull request merged**
