### PR TITLE
Categories

### PR DESCRIPTION
**Pull request by maelle**
cf #28 

A few questions

* It seems suboptimal to update it once in a while. 
		* When a package is onboarded, should the editor/a member of staff (editors are volunteers, with already a lot of things to do) add an entry in the CSV? Or do we want the category info to live in the package?
		* Same question for when a member of staff creates/transfer a new package.

* Are the categories ok? data-access, data-tools, http-tools, literature, scalereprod, databases, security, data-publication, geospatial, data-visualization, image-processing, taxonomy, data-extraction, data-analysis and altmetrics.

* These packages without category info should be removed from the registry in my opinion: craft, miner, rcheatsheet, roblog and umapr. I'll make a PR to makeregistry.

* Should makeregistry and roregistry be merged?

### CODE REVIEW

**Comment by maelle** [comment]
Should have I updated https://github.com/ropenscilabs/makeregistry/blob/master/inst/scripts/final_categories.csv instead? :cold_sweat: 

No https://github.com/ropenscilabs/makeregistry/blob/cfe283a6d52131fac9fe41d97a6aa884ba8c6d6d/R/registry.R#L131 but we could store the categories.csv in makeregistry if that's used there.

**Comment by sckott** [comment]
> Or do we want the category info to live in the package?

where would that go exactly?

> Are the categories ok? 

i forget where we're at on categories. are those the categories currently used in our software-review?  if so, that looks good to me then

> These packages without category info should be removed

agreed

> Should makeregistry and roregistry be merged?

hmm, at this point this repository is mostly just commits from the bot with the built registry - so maybe it makes sense to keep roregistry as the built registry with bot commits only - and makeregistry has everything else. sound good?

> Should have I updated .../final_categories.csv instead?

see above comment, yeah, lets keep all the scripts/metadata/etc in makeregistry

**Comment by maelle** [comment]
The categories are for https://ropensci.org/packages

**Comment by maelle** [comment]
Ok, will close this here and instead will update makeregistry.

Reg categories in packages that could live in DESCRIPTION as schema.org stuff but not that straightforward.

**Pull request closed without merging**
