### PR TITLE
add pkgmatch to not_transferred

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Review by maelle — APPROVED** [review]
Don't forget to squash and merge! :smile_cat:

**Comment by mpadge** [comment]
I can't, as far I know about stuff, because I've committed to same branch in my repo. I knew I shouldn't've done that ... Shall I close this and start another from a different branch? Or do you know a way to get there via PR from same branch?

**Comment by maelle** [comment]
the diff was clean so I just clicked the button, didn't realize you didn't have access.

**Comment by mpadge** [comment]
Cool, thank you! That's just so I can get the docs generated

**Comment by maelle** [comment]
With this commit you'll also get this package listed in the newsletter :grin:

**Pull request merged**
